### PR TITLE
Implement upload iso  and  optimize PveClientBase header

### PR DESCRIPTION
**Pull request by 390620652**
1 Implement upload iso function

[https://github.com/Corsinvest/cv4pve-api-dotnet/issues/16](url)

2 use HttpRequestMessage  to optimize PveClientBase header. Avoid enforcing a uniform header globally.

### CODE REVIEW

**Comment by franklupo** [comment]
I can't get it to work.
Can you attach an example? 

Best regatds

**Comment by 390620652** [comment]
```
var client = new PveClient(config.Host, config.Port);
await client.LoginAsync(config.User,config.Password);
string filePath = "D:\\test.iso";
var stream = File.OpenRead(filePath);
var result = await client.Nodes["pve"].Storage["local"].Upload.Upload(stream, "test2.iso", "iso");
```
screenshot-20240708-142341

**Comment by 390620652** [comment]
> I can't get it to work. Can you attach an example?
> 
> Best regatds



> I can't get it to work. Can you attach an example?
> 
> Best regatds

do you see it ?

**Comment by 390620652** [comment]
> I can't get it to work. Can you attach an example?
> 
> Best regatds

do you see it ?

**Comment by franklupo** [comment]
next week create new release

best reagrds

**Comment by franklupo** [comment]
I created UploadFileToStorageAsync in the extension. 

Thanks for your contribution.

**Pull request closed without merging**
